services:
  self-service-mysql:
    image: mysql
    container_name: LocalVenueMySQL
    environment:
      - MYSQL_ROOT_PASSWORD=!BAT4CHAT
      - Name=LocalVenueMySQL
    ports:
      - "3306:3306"
    networks:
      - app-network

  app:
    build:
      dockerfile: Dockerfile
    container_name: LocalVenue
    depends_on:
      - self-service-mysql
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
