name: Postman Tests

on:
  push:
    branches:
      - master
    paths:
      - "LocalVenue/**"
      - ".github/workflows/on-merge-workflow.yml"
      - "LocalVenue Tests.postman_collection.json"

jobs:
  xunit-test:
    uses: ./.github/workflows/dotnet-build-test-publish.yml

  deploy:
    runs-on: ubuntu-latest
    needs: xunit-test

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "localvenue-webapp-casp0006"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

  postman-test:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make directory for newman results
        run: mkdir newman

      - name: Run Postman tests
        run: |
          newman run "LocalVenue Tests.postman_collection.json" \
            --env-var "webUrl=https://localvenue-webapp-casp0006.azurewebsites.net/" \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export testResults/runreport.html \
            --reporter-htmlextra-darkTheme

      - name: Publish Postman results
        uses: actions/upload-artifact@v4
        with:
          name: RunReports
          path: testResults
