name: On PR workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "LocalVenue/**"
      - "LocalVenue.Tests/**"
      - ".github/workflows/pr-workflow.yml"

jobs:
  format-lint:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          dotnet tool restore
          dotnet csharpier --check .

  xunit-test-with-sonarcloud:
    name: Test and Analyze
    needs: format-lint
    uses: ./.github/workflows/dotnet-build-test-publish.yml
    secrets: inherit
    with:
      publish: false
