name: .NET Tests

on:
  push:
    branches: ["master"]
    paths:
      - "LocalVenue/**"
      - "LocalVenue.Tests/**"
      - ".github/workflows/pr-workflow.yml"
  pull_request:
    branches: ["master"]
    paths:
      - "LocalVenue/**"
      - "LocalVenue.Tests/**"
      - ".github/workflows/pr-workflow.yml"

jobs:
  xunit-test:
    uses: ./.github/workflows/dotnet-build-test-publish.yml
