name: On PR workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "LocalVenue/**"
      - "LocalVenue.Tests/**"
      - ".github/workflows/pr-workflow.yml"

jobs:
  format-lint:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Install csharpier
        run: dotnet tool install -g csharpier

      - name: Run dotnet csharpier
        run: dotnet csharpier --check .

  xunit-test-with-sonarcloud:
    name: Test and Analyze
    needs: format-lint
    uses: ./.github/workflows/dotnet-build-test-publish.yml
    secrets: inherit
    with:
      publish: false
