name: On PR workflow

on:
  push:
    branches: ["master"]
    paths:
      #     - "LocalVenue/**"
      #     - "LocalVenue.Tests/**"
      - ".github/workflows/pr-workflow.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "LocalVenue/**"
      - "LocalVenue.Tests/**"
      - ".github/workflows/pr-workflow.yml"

jobs:
  format-lint:
    name: Format and Lint
    secrets: inherit
    uses: ./.github/workflows/dotnet-format-lint.yml

  xunit-test-with-sonarcloud:
    name: Test and Analyze
    needs: format-lint
    uses: ./.github/workflows/dotnet-build-test-publish.yml
    secrets: inherit
    with:
      publish: false
